:run_tasks:
  increment_version: false
  decorate_icon: false
  xcode_build: true
  create_ipa: false
  run_tests: false
:options:
  :app_name: "App"
  :scheme:
  :configuration: "Release"
  :code_sign: "iPhone Distribution: LBi UK"
  :provisioning_profile: "ContinuousIntegrationTest.mobileprovision"
  :app_dir:
  :icons_path:
  :build_dir_path:
