# iOS Build Process Configuration
# -------------------------------
# This is the default build configuration, override by copying the file and passing to the build tool with:
# $ `rake default [your_config_file.yml]`

:run_tasks:
  increment_version: true														# increments the build version number in the app-info.plist
  decorate_icon: false															# overlays the version number on the app icon	
  xcode_build: false																# runs the xcodebuild command to build the app
  run_tests: false																	# run unit tests																													
  create_ipa: false																	# packages the app into an .ipa for distribution
:options:
  :app_name: "APPNAME"															# Name of the Application (this should auto-set running configure.rb)
  :app_dir:																					# The app folder (conatins code, reources, plist etc). default: :app_name/:app_name
  :scheme:																					# Build scheme (defaults to the "App" scheme included with the workspace)
  :build_configuration:															# Build configuration (defaults to "Release")
  :code_sign: "iPhone Distribution: LBi UK"					# Code signing identity
  :provisioning_path:																# Provisioning profile location (defaults to "../Provisioning/")
  :provisioning_profile: "CITest.mobileprovision"		# Provisioning profile file in '../Provisioning/' directory (REQUIRED for create_ipa)
  :app_dir:																					# App directory name (defaults to app_name, override to change)																																	
  :icon_path:																				# Path to icon directory (defaults to '<app_dir>/Resources/Assets/Images/Icon/', override to change)
  :build_dir_path:																	# Path to build directory (defaults to 'builds/', override to change)
  :sdk:																							# Build SDK. Default: iphoneos